services:
  - type: web
    name: refiq
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: ADMIN_KEY
        sync: false
